### ISSUE TITLE
Auto filters not included in the output after rendering

### ISSUE THREAD

**Issue by rosshug** [zhangyu836/xltpl#10]
I created an xlsx template, with column headers in the first row, and set auto filters on (Data > Filter menu in Excel). The results after rendering were correct except that the auto filter was missing.

I corrected this in the package code on my PC by copying the auto_filter setting in basex.py, SheetBase.copy_sheet_settings()
`self.wtsheet.auto_filter = copy.copy(self.rdsheet.auto_filter)`

This worked fine in my case, because I had filters on the first row, however it will not work properly if the result of rendering moves the position of the cells being filtered.

**Comment by zhangyu836** [comment]
Support for auto filter has been added. 
Please upgrade you xltpl package.

**Comment by rosshug** [comment]
Thanks, works for me. Sorry about delay on closing.
