### ISSUE TITLE
image

### ISSUE THREAD

**Issue by mufeng272933** [zhangyu836/xltpl#11]
The image function in the example does not work.

**Comment by zhangyu836** [comment]
xltpl uses xlrd to read and xlwt to write xls file.
xlrd does not extract images, datavalidations or autofilter.
xltpl uses openpyxl to read and write xlsx file.
openpyxl uses Pillow to fetch image object.
If Pillow not installed or Pillow can not locate image file.
{%img v%} will be ignored.

**Comment by mufeng272933** [comment]
I'm sure that pillow is installed, but the example don't work on my computer

**Comment by zhangyu836** [comment]
Would you like to upload the generated files, and provide version numbers of the os, python, xltpl, openpyxl, pillow?

**Comment by mufeng272933** [comment]
[examples.zip](https://github.com/zhangyu836/xltpl/files/7843788/examples.zip)
This is my configuration and thank you.

**Comment by zhangyu836** [comment]
It seems that the images other than the last one in the 'image' worksheet have been deleted or moved, causing {%img v%} to be ignored.

**Comment by mufeng272933** [comment]
I am looking forward to your continuous improvement

**Comment by zhangyu836** [comment]
{%img v%} must be in the first cell of the range covered by the image.

**Comment by mufeng272933** [comment]
isn’t it right? I don't think I violated what you said

**Comment by zhangyu836** [comment]
The first cell of the range covered by the image is the cell corresponding to the coordinates of the top-left of the image. 
It could be part of a merged cell, and is not visible. 
In such a case, you can unmerge the merged cell and move the variable to the appropriate cell.

**Comment by mufeng272933** [comment]
in fact it's not a merged cell. I stretched it.

**Comment by zhangyu836** [comment]
Upgrade your xltpl and retry.

**Comment by mufeng272933** [comment]
it doesn't work either.

**Comment by zhangyu836** [comment]
Upload your file.
Let's see how to make it work.

**Comment by mufeng272933** [comment]
[xlstpl_test.zip](https://github.com/zhangyu836/xltpl/files/7893543/xlstpl_test.zip)

**Comment by zhangyu836** [comment]
You need to insert an image as a reference so that xltpl can determine the position, size of the image to be generated.

**Comment by mufeng272933** [comment]
I'm ready to give up. Maybe xlwings is also a good choice

**Comment by zhangyu836** [comment]
ok

**Comment by zhangyu836** [comment]
Inserted a reference image in Sheet1.

lo_info={'pic':pic}
lo_info={'test':'test'}

changed to 

lo_info={'pic':pic}
lo_info['test'] = 'test'

[xlstpl_test.zip](https://github.com/zhangyu836/xltpl/files/7893933/xlstpl_test.zip)

**Comment by mufeng272933** [comment]
i'm sorry about that but it doesn't work.Thank you just the same.
















At 2022-01-19 11:43:11, "Zhang Yu" ***@***.***> wrote:

Inserted a reference image in Sheet1.

lo_info={'pic':pic}
lo_info={'test':'test'}

changed to

lo_info={'pic':pic}
lo_info['test'] = 'test'

xlstpl_test.zip

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
