### ISSUE TITLE
Column not written when nested list is empty

### ISSUE THREAD

**Issue by fbarre96** [zhangyu836/xltpl#16]
I tried to use nested loop to write data in my sheet and a column is missing in the final excel output if a the nested list is empty.
Here is the code I tried with the template [template.xlsx](https://github.com/zhangyu836/xltpl/files/10372210/template.xlsx)  :
```
from xlsxtpl.writerx import BookWriter

writer = BookWriter('template.xlsx')
writer.jinja_env.globals.update(dir=dir, getattr=getattr)
# Define the data that you want to fill into the template
data = {
    'persons':[
        {
            'name': 'John',
            'children':[
            ],
            'age': 28
        },
        {
            'name': 'Peter',
            'children':[
                {'name':'Ana'},


                {'name':'Eve'}
            ],
            'age': 49
        }

    ],
   
}

writer.render_book(payloads=[data])
# Create a new workbook
writer.save("out.xlsx")
```
This is what was generated : [out.xlsx](https://github.com/zhangyu836/xltpl/files/10372219/out.xlsx).

the expected output would be an empty B2 cell and the data "28" in the C2 cell instead of the B2 cell.

**Comment by zhangyu836** [comment]
This is expected behavior.
Try this
[template.xlsx](https://github.com/zhangyu836/xltpl/files/10397892/template.xlsx)

**Comment by fbarre96** [comment]
This solved my issue thanks
