### ISSUE TITLE
模板表头中合并的单元格生成报表后合并单元格的属性丢失了

### ISSUE THREAD

**Issue by bruthliu** [zhangyu836/xltpl#3]
模板表头中的合并单元格样式：
![template](https://user-images.githubusercontent.com/30863051/84333170-86fd3380-abc1-11ea-9f3d-ed2a731a1b40.png)

生成报表中的表头保并单元格的表头格式乱了：
![after](https://user-images.githubusercontent.com/30863051/84333174-89f82400-abc1-11ea-89d8-be44f0e4a049.png)

**Comment by bruthliu** [comment]
请大神帮忙看看如何解决解决。谢谢。

**Comment by zhangyu836** [comment]
excel文件发出来看一下

**Comment by bruthliu** [comment]
附件请查收。
[temple--20200610.xlsx](https://github.com/zhangyu836/python-xls-xlsx-template/files/4762381/temple--20200610.xlsx)

**Comment by zhangyu836** [comment]
试了一下，没有发现问题。
或许你可以更新一下 xltpl。

**Comment by bruthliu** [comment]
![image](https://user-images.githubusercontent.com/30863051/84454472-2f2bfe80-ac8d-11ea-8243-494f3c49ab6c.png)

已解决，谢谢大神。
解决方法：
更新xltpl至0.2.2后，我又更新six==1.15.0，jdcal==1.4.1，openpyxl==3.0.3，解决问题。
（单独更新xltpl至0.2.2未解决问题。）
