### ISSUE TITLE
页眉页脚丢失

### ISSUE THREAD

**Issue by Gaoshimin** [zhangyu836/xltpl#4]
感谢作者的分享，这里有个小问题：原模板有页眉页脚信息，生成的文件中没有页眉页脚，能否提供相应支持？

**Comment by zhangyu836** [comment]
已经更新代码。
请试一下。
页眉页脚需要使用 自定义页眉页脚 同时指定 左中右，可以填入空格。
否则 openpyxl 会发出警告。
