### ISSUE TITLE
原模版文件中单元格数据验证怎样能保留

### ISSUE THREAD

**Issue by chenbotao828** [zhangyu836/xltpl#5]
大佬好，如题，例如：
原模版文件中，一些单元格包含数据验证，如何在输出文件中保留这一点，谢谢

openpyxl中指的是data validation可以读写，理论上应该可以做到，希望大佬能支持 谢谢！

**Comment by zhangyu836** [comment]
这个稍微有点复杂，以后解决。
你可以发个示例，供参考。

**Comment by zhangyu836** [comment]
增加了对于data validation的处理，请试一下。

**Comment by chenbotao828** [comment]
大佬牛逼！

**Comment by deOctagon** [comment]
Hi,
Was this issue fixed? I am still not seeing data validation preserved in the output file.

Many thanks and kind regards,
