### ISSUE TITLE
能否添加对图片的支持

### ISSUE THREAD

**Issue by liangwind** [zhangyu836/xltpl#6]
您好，excel模板中有logo图片的话，生成的文件中图片丢失，请问有没有解决办法。

**Comment by zhangyu836** [comment]
发个示例看一下

**Comment by chenbotao828** [comment]
模板文件中有图片，生成的文件中图片就没了。

**Comment by zhangyu836** [comment]
请上传一个包含你们所说的logo/图片的xlsx示例文件。

**Comment by zhangyu836** [comment]
现在会复制图片，但不对图片位置进行任何处理。
请试一下。

**Comment by zhangyu836** [comment]
需要安装pillow，openpyxl 才会读入图片。

**Comment by Gaoshimin** [comment]
实测现在可以正常显示图片了，之前版本会导致图片丢失
