### ISSUE TITLE
如何写入图片？如：生成二维码图片后，写入到模板的指定位置

### ISSUE THREAD

**Issue by Gaoshimin** [zhangyu836/xltpl#7]
大神你好，工具是否支持图片写入？

我的需求是这样：用excel打印类似于快递单那样的标签，标签中内容除了文字以外还有二维码用于扫码，我用excel做好了模板，然后python代码生成了二维码图片，使用 xltpl 能正常写入文字信息，但是二维码图片不知如何写入

**Comment by zhangyu836** [comment]
请升级为 v0.8，然后参照 examples/images.py, images.xlsx 处理。

**Comment by Gaoshimin** [comment]
非常感谢作者！提出issue后很快进行了更新，现在可以写入图片了，还提供了example。谢谢！
