### ISSUE TITLE
写入数字后，生成的EXCEL中变成了字符串形式的数字，需要手动进行转换类型才能进行计算，能否在写入后还保留数字类型？

### ISSUE THREAD

**Issue by Gaoshimin** [zhangyu836/xltpl#8]

**Comment by zhangyu836** [comment]
使用{%xv var%}形式来指定变量。单元格中只有一个{%xv var%}形式的变量时，输出为 var 的类型，使用在单元格上设置的样式显示，否则与{{var}}一样输出字符串。
不确定这是否就是你所需要的。

**Comment by Gaoshimin** [comment]
我使用{%xv var%}提示“Encountered unknown tag 'vx'“错误，我的问题是这样，请见下图：
<img width="557" alt="屏幕截图 2021-04-06 102353" src="https://user-images.githubusercontent.com/27984301/113650627-192b7680-96c3-11eb-92cb-0ae00cdf0318.png">

**Comment by zhangyu836** [comment]
是 {%xv var%} 不是 {%vx var%}。
应该是你填错了。
如果不是，把你的模板文件发来看一下。

**Comment by Gaoshimin** [comment]
感谢提醒，确实是我写错了，使用{%xv var%}可以正常输出数字
