### ISSUE TITLE
请问如何设计模板，让填充的表格等份、出现在多页上

### ISSUE THREAD

**Issue by retsyo** [zhangyu836/xltpl#9]
例如，有100人的信息，要填到excel文件里，但是要求
1. 每一页最多只放30人的数据，
2. 每一页的表格并不占满纸张，而是在这一页的表格下方有若干空行

以上这样做的目的，是方便打印后观看

那么，应该怎么样设计模板，实现每30行（如果加标题，就是31行数据；其实第一页可能更复杂，比如第一行还写着“302班成绩表”，不过这一行的数据，手工添加也可以）占据打印时的一张纸？
谢谢啊

第一页的表，

| 学号 | 姓名   | 语文 | 数学 |
| ---- | ------ | ---- | ---- |
| 001  | 孙悟空 | 80   | 90   |
| 002  | 猪八戒 | 90   | 50   |
| ...  |        | ...  | ...  |
| 030  | 唐僧   | 100  | 90   |

第4页的表
| 学号 | 姓名   | 语文 | 数学 |
| ---- | ------ | ---- | ---- |
| 091  | 宋江   | 80   | 90   |
| 092  | 武松   | 90   | 50   |
| ...  |        | ...  | ...  |
| 100  | 孙二娘 | 100  | 90   |

**Comment by zhangyu836** [comment]
设计多个worksheet模板，对数据进行预处理（分页等等），不同的数据根据需要使用不同的模板

**Comment by zhangyu836** [comment]
设计多个worksheet模板，对数据进行预处理（分页等等），不同的数据根据需要使用不同的模板
